// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEKdYOfDJPnE_O          ri0_DRD86SzflklTjg',
    appId: '1:638998238604:web:211fe724d1f8cc5adbb2a9',
    messagingSenderId: '638998238604',
    projectId: 'abc123-2580c',
    authDomain: 'abc123-2580c.firebaseapp.com',
    storageBucket: 'abc123-2580c.firebasestorage.app',
    measurementId: 'G-6NEFEHNP2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIt5MtwGPE7KSmNAMNeX6qoU77LXkxTVI',
    appId: '1:638998238604:android:0fb222fa219704cddbb2a9',
    messagingSenderId: '638998238604',
    projectId: 'abc123-2580c',
    storageBucket: 'abc123-2580c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvrywsVo_DfyLkVUvObmILLE-PZajWYw',
    appId: '1:638998238604:ios:2ad1f7f45000b718dbb2a9',
    messagingSenderId: '638998238604',
    projectId: 'abc123-2580c',
    storageBucket: 'abc123-2580c.firebasestorage.app',
    iosBundleId: 'com.example.abcd1234',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwvrywsVo_DfyLkVUvObmILLE-PZajWYw',
    appId: '1:638998238604:ios:2ad1f7f45000b718dbb2a9',
    messagingSenderId: '638998238604',
    projectId: 'abc123-2580c',
    storageBucket: 'abc123-2580c.firebasestorage.app',
    iosBundleId: 'com.example.abcd1234',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvEKdYOfDJPnE_Ori0_DRD86SzflklTjg',
    appId: '1:638998238604:web:7304b95e22ac50a5dbb2a9',
    messagingSenderId: '638998238604',
    projectId: 'abc123-2580c',
    authDomain: 'abc123-2580c.firebaseapp.com',
    storageBucket: 'abc123-2580c.firebasestorage.app',
    measurementId: 'G-QKR4RD459P',
  );
}
