// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJaeTtmF2BSKNajm5ugUrsLpFRIgtPoes',
    appId: '1:326925590248:web:262dfa5e0b0b5a7855735d',
    messagingSenderId: '326925590248',
    projectId: 'bnk-app-push',
    authDomain: 'bnk-app-push.firebaseapp.com',
    storageBucket: 'bnk-app-push.firebasestorage.app',
    measurementId: 'G-H951TZ1LHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9MUdq_vapNafXp5nAxRbxKPGmyxZL09w',
    appId: '1:326925590248:android:dc8eaa1b46cc28a855735d',
    messagingSenderId: '326925590248',
    projectId: 'bnk-app-push',
    storageBucket: 'bnk-app-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DTiJQMpVCS_HWL0AGXjLZ6-9IxQy710',
    appId: '1:326925590248:ios:3b6df47ec0cc9d3055735d',
    messagingSenderId: '326925590248',
    projectId: 'bnk-app-push',
    storageBucket: 'bnk-app-push.firebasestorage.app',
    iosBundleId: 'com.example.reframe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7DTiJQMpVCS_HWL0AGXjLZ6-9IxQy710',
    appId: '1:326925590248:ios:3b6df47ec0cc9d3055735d',
    messagingSenderId: '326925590248',
    projectId: 'bnk-app-push',
    storageBucket: 'bnk-app-push.firebasestorage.app',
    iosBundleId: 'com.example.reframe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJaeTtmF2BSKNajm5ugUrsLpFRIgtPoes',
    appId: '1:326925590248:web:0df5bc1f2d66a61555735d',
    messagingSenderId: '326925590248',
    projectId: 'bnk-app-push',
    authDomain: 'bnk-app-push.firebaseapp.com',
    storageBucket: 'bnk-app-push.firebasestorage.app',
    measurementId: 'G-3Q5FYPHGBR',
  );
}
